### ISSUE TITLE
Feature: add eth_submitTransaction

### ISSUE THREAD

**Issue by kumavis** [MetaMask/web3-provider-engine#113]
new alias for `eth_sendRawTransaction` as introduced by parity

**Comment by flyswatter** [comment]
Since some users run their own nodes, encouraging Ðapp developers to use parity-only APIs makes those Ðapps less resilient in the case of parity failures, when Infura may switch to less affected clients, as well as excluding MetaMask users who are not using Parity.

**Comment by flyswatter** [comment]
Oh unless we do the alias client-side, which is probably what you were proposing. I'm up too late!

**Comment by mcmire** [comment]
Closing this since we're actively phasing out this package in favor of `json-rpc-engine`. Do we do this now? If not, then an appropriate place to raise this would probably be `eth-json-rpc-middleware`.
