### ISSUE TITLE
Feature: Add `personal_decryptMessage` method.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/web3-provider-engine#168]
We could simply match the API for `parity_decryptMessage` but without the platform-specific prefix:

https://github.com/paritytech/parity/wiki/JSONRPC-parity-module#parity_decryptmessage

Would be a de-facto implementation of EIP 130:
https://github.com/ethereum/EIPs/issues/130#issuecomment-309389060

**Comment by flyswatter** [comment]
Should be inter-compatible with a paired method on `eth-sig-util`:
https://github.com/MetaMask/eth-sig-util/issues/2

**Comment by AgeManning** [comment]
Hey, is there any update on this. 
I've got a small dapp which requires this decryption. I understand EIP130 is not yet implemented. I've built a javascript/browser implementation to perform the encryption/decryption (https://github.com/sigp/ecies-parity) to match Parity's implementation.
I had intended to use the parity-chrome extension, which injects parity's web3 which contains the decrypt method, however Parity is no longer supporting this officially. Metamask seems to be the primary browser extension to interact with dapps. 
In it's current form, my dapp will have to get the private key to be entered directly (not ideal), but a metamask decryption feature would resolve this. 
I understand this feature is not implemented in other clients, but I could make a pull request to implement this to metamask if it were still desired.

**Comment by mcmire** [comment]
Since we have effectively deprecated this package in favor of `json-rpc-engine` and its related packages and are no longer incorporating new changes, I'm going to close this. If we still want this feature we might consider adding it to `eth-json-rpc-middleware`.
