### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by tcoulter** [MetaMask/web3-provider-engine#20]
My bundled file grew by ~5 Mb once I added the provider engine as a dependency. That's unminified, but still once I minify it it's roughly 4 Mb. That's way too big for a browser app -- for mobile anyway. 

I think there are some dependencies we can remove. Here are some quick suggestions:
- `async` - nicety, but we don't need the whole library for the little we use it.
- `ethereumjs-utils` - it's used for minor hex stripping and conversion to buffers. We can get buy without it for most cases.

Will look for more.

**Comment by flyswatter** [comment]
Would this be included in every web app, or would this mostly be powering the browser extension?On Jan 28, 2016, at 4:14 PM, Tim Coulter <notifications@github.com> wrote:My bundled file grew by ~5 Mb once I added the provider engine as a dependency. That's unminified, but still once I minify it it's still ~4 Mb. That's way too much for a browser app (at least, for mobile anyway). I think there are some dependencies we can remove. Here's some quick suggestions, though I need to look into it more:



async - nicety, but we don't need the whole library for the little we use it.

ethereumjs-utils - it's used for minor hex stripping and conversion to buffers. We can get buy without it for most cases.
Will look for more.—Reply to this email directly or view it on GitHub.

**Comment by tcoulter** [comment]
I'm not sure how this works wrt the browser extension. @kumavis would have to weigh in.

**Comment by kumavis** [comment]
> Would this be included in every web app, or would this mostly be powering the browser extension?
potentially both. it goes in the browser extension (which zipped is less than 2mb) but also optionally into the dapp so they can fallback without mist/metamask

**Comment by kumavis** [comment]
regarding managing bundle size:
* make sure you're measuring the size with js sourcemaps off, i've experienced them doing 6x size increases!
* [disc](http://hughsk.io/disc/) is a great tool for tracking down what modules are actually large in your dep graph -- I would do this before taking out modules on whim

**Comment by kumavis** [comment]
did some tests. bundle source:
```js
require('web3-provider-engine/example.js')
```
This example includes light-wallet, vm, the whole shebang.
here is some data im seeing on the bundle:
```
3.9M bundle.browserify.js
2.0M bundle.browserify.min.js

3.6M bundle.webpack.js
1.5M bundle.webpack.min.js
```
note that while the source is tested in node, these builds are untested. webpack may not be including some node/browserify globals like `Buffer`. I am not familiar with its behavior.

Here's disc's output (its interactive)
![image](https://cloud.githubusercontent.com/assets/1474978/12668127/6f16a588-c608-11e5-9964-2f009c9f81fe.png)

At first glance a couple of the offenders:
* [bitcore-lib](https://github.com/bitpay/bitcore-lib) (lightwallet)
* [lodash](https://github.com/lodash/lodash) (lightwallet > bitcore-lib)
* [ethereum-common](https://github.com/ethereum/common) (ethereumjs-tx, ethereumjs-block, etc)

theres also a variety of crypto and bignumber libs that could potentially be reduced

**Comment by kumavis** [comment]
Actually tried disc on the minified source and it paints a slightly different picture:

[![image](https://cloud.githubusercontent.com/assets/1474978/12668586/f003dc7a-c60c-11e5-914c-cf7b290c89c3.png)](https://jsbin.com/voyeciyuna)

`ethereum-common` is incompressible (and totally unneeded here)
ping @wanderer

**Comment by kumavis** [comment]
Here is an unminified bundle w/o lightwallet

[![image](https://cloud.githubusercontent.com/assets/1474978/12668720/58131e9c-c60e-11e5-9489-2c2181f753b3.png)](https://jsbin.com/bupitososa)

primary offenders are:
* ethereum-common
* es6-shim x2 (ethereumjs-block, ethereumjs-vm)
* elliptic x2 (ethereumjs-account+ethereumjs-tx, browser-crypto)
* bn.js x2 (browser-crypto)
* bluebird (ethereumjs-tx > secp256k1)

**Comment by kumavis** [comment]
in summary:
* lightwallet is a big player here and can be improved
* ethereumjs is bringing along `ethereum-common` and possibly browser-crypto, the shim for `require('crypto')`

additionally note that provider-engine is essentially an entire ethereum client, not some helper lib, so its going to be a bit chunky.

**Comment by wanderer** [comment]
https://github.com/cryptocoinjs/secp256k1-node/pull/57 Will get rid of bluebird

**Comment by wanderer** [comment]
i'm not sure how to deal with ethereum-common though. Its just pure json files.

**Comment by axic** [comment]
> elliptic x2 (ethereumjs-account+ethereumjs-tx, browser-crypto)

This should be solved with the upcoming releases. All crypto is in ethereumjs-util (which depends on secp256k1).

**Comment by kumavis** [comment]
awesome

**Comment by axic** [comment]
@kumavis @wanderer we could also split out the crypto functions into `ethereumjs-crypto` and thus leave `ethereum-utils` much smaller (no secp256k1 dep)

**Comment by kumavis** [comment]
@axic I like this idea

**Comment by axic** [comment]
Added a change to ethereumjs-common (https://github.com/ethereumjs/common/commit/3d79d3b2c038054e567a1614685e2011949ff891) so hopefully ethereumjs-tx will be updated soon, removing the genesis data from it.

**Comment by kumavis** [comment]
thanks @axic!

**Comment by axic** [comment]
That change is out there with common@0.0.17 and ethereumjs-tx@1.1.1. No need to update provider-engine given semver does the job.

My build is only 1.5MB which includes React, provider-engine, web3, ethereumjs-wallet, ethereumjs-tx and all the deps of these. I think that is a fair bundle size.

**Comment by tcoulter** [comment]
:clap:
