### ISSUE TITLE
Filters - Two instances of event listener lead to empty arguments

### ISSUE THREAD

**Issue by traycho** [MetaMask/web3-provider-engine#206]
Hello,

I am using ZeroClientProvider as my web3 provider and once I created a new instance to listen to transfer events, the events are received but the arguments are empty with default value 0x.

Transfer event is standard  ERC20  token Transfer event.

``
contract.Transfer({}, { fromBlock: 0 , toBlock: 'latest'}, function (error, result) {
      console.log(result);
});
``

``
contract.Transfer({}, { fromBlock: 0 , toBlock: 'latest'}, function (error, result) {
      console.log(result);
});
``

Note only args  values are empty , args: {from: "0x", to: "0x", value: BigNumber} all the rest properties are fine. If I use the default web3 provider it works without a problem.

**Comment by kumavis** [comment]
just replaced the filter implementation
