### ISSUE TITLE
Custom RPC doesn't resolve capital URLs HTTP vs http

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/web3-provider-engine#237]
![screenshot from 2018-04-30 17-18-18](https://user-images.githubusercontent.com/13376180/39456396-0190f6c8-4c9b-11e8-9f9f-dfa96bebb231.png)

**Comment by mcmire** [comment]
Closing since we have effectively deprecated the use of this package and are no longer making any bugfixes.
