### ISSUE TITLE
14.0.5 breaks React builds

### ISSUE THREAD

**Issue by rsmylskibc** [MetaMask/web3-provider-engine#239]
As of version 14.05, eth-block-tracker was updated from 2.3.1 to 3.0.1, which no longer contains es5 safe code, and prevents react apps from building.

**Comment by gbalabasquer** [comment]
Is there any updates on this issue?

**Comment by gbalabasquer** [comment]
I have the same problem with all the 14.* versions, does it work 14.0.4 for you?

**Comment by rsmylskibc** [comment]
To you have to import from `dist/es5` dir - https://github.com/MetaMask/provider-engine/issues/218

**Comment by gbalabasquer** [comment]
Ah yes, I was using the incorrect path. Now with 14.0.4 works. With 14.0.5 same issue with `eth-block-tracker` sub-dependency.
Thanks a lot.

**Comment by kumavis** [comment]
sorry that it got released in a patch :pray:
