### ISSUE TITLE
Using web3 1.0 subscribe with provider engine

### ISSUE THREAD

**Issue by alexbourdon** [MetaMask/web3-provider-engine#248]
I having trouble understanding how to use the subscribe with the provider engine.

when I use the engine events they come in fine, and when I use subscribe with only the web3 1.0 (no engine), they work fine. But when I use the engine and use web3.eth.subcribe I get nothing in the call back. I see the web socket on the network using the subscription id, but no result:

var engine = new Web3ProviderEngine()
  var web3 = new Web3(engine)
  engine.addProvider(new WebSocketSubProvider({
    rpcUrl: 'wss://...'
  }))
  engine.addProvider(new SubscriptionSubprovider())
  engine.start()

 var subscription = web3.eth.subscribe('newBlockHeaders', function (error, result) {
    if (error) {
        console.log(error)
    }
  })
  .on('block', function (blockHeader) {
      console.log(blockHeader)
    })

**Comment by jamespic** [comment]
Yes, there's some extra wiring you need to add, that's not well-documented. Add something like the following:

```
subscriptionSubprovider.on('data', (err, notification) => {
  engine.emit('data', err, notification)
})
```

**Comment by kumavis** [comment]
this happens by default now
