### ISSUE TITLE
How to customize the sendTransaction method？

### ISSUE THREAD

**Issue by silence-may** [MetaMask/web3-provider-engine#263]
excuse me : 
        I have such a requirement, I need to take over the sendTransaction method, I will do some other operations when the user initiates this method, such as popping up a pop-up window, etc. I noticed that hooked-wallet.js seems to allow me to Define the method of sending the transaction, but I only see some operations through signTransaction, what should I do? Please give me some suggestions!

**Comment by ahmb84** [comment]
@silence-may 
Hi!, 
If you want to show a pop-up are anything like that yes you have to do it in the signTransaction method in hooked-wallet.js, here web3 send the tx params and then you could play with and most important sign the tx with the private key of the user.

Best.

**Comment by kumavis** [comment]
in metamask we don't use the hooked-wallet and just wrote our own custom hooks
