### ISSUE TITLE
Using web3 1.0 events

### ISSUE THREAD

**Issue by jvluso** [MetaMask/web3-provider-engine#283]
I am trying to use the event emitter from a web3 instance from a custom provider as described in https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#events . Is this possible yet? It works when using a websocket provider.

**Comment by AndriianChestnykh** [comment]
The same question from my side. Is this possible? @jvluso , have you figured it out?

**Comment by jvluso** [comment]
https://github.com/jvluso/aragon.js/blob/wallet-provider-2/packages/aragon-wallet-provider/src/index.js This is what I created. I had to add several event related functions, though I don't remember which ones they were. I also found out that this method of providing a web3 instance is starting to be deprecated and replaced with the keyrings like https://github.com/MetaMask/eth-hd-keyring .

**Comment by kumavis** [comment]
It should work via the filters+subscriptions polyfill
https://github.com/MetaMask/provider-engine/blob/master/zero.js#L44-L51

if its not working, i need a clearer failure repro

**Comment by kumavis** [comment]
seems like a common gotcha is forgetting to forward the events onto the provider-engine from the middleware
https://github.com/MetaMask/web3-provider-engine/blob/24e4f18ac040ec170455aedee637d20360845db3/zero.js#L47-L49

I'll make that happen automatically in v15
