### ISSUE TITLE
`mustProviderInConstructor` would not be executed

### ISSUE THREAD

**Issue by samueltangz** [MetaMask/web3-provider-engine#307]
In https://github.com/MetaMask/web3-provider-engine/blob/master/subproviders/hooked-wallet.js#L71 (and lines 72, 73 & 74), `mustProviderInConstructor('signTransaction')` would not be called, no matter if `opts.signTransaction` is truthy or falsey.

It has been requested in line 7 that user should implement `getAccounts` and `signTransaction`.  However in the constructor, none of them is actually required.

**Comment by kumavis** [comment]
yep, thanks, fixed
