### ISSUE TITLE
Calling Web3ProviderEngine.prototype.send function throws error

### ISSUE THREAD

**Issue by abhayks1** [MetaMask/web3-provider-engine#309]
Hi Team,

Thank you for the Web3ProviderEngine. 
We use it in https://github.com/OpenST/JLP/tree/master/src.

What can we do to use it in a project that uses a library that uses `.send`?

**Problem Description**

We are facing below issue while consuming this library in our project.
Web3 has removed **sendAsync** method both from HttpProvider as well as WebsocketProvider.
https://github.com/ethereum/web3.js/issues/1451

It has started supporting only **.send** function.
However Web3ProviderEngine supports **.sendAsync** function and throws error on calling **.send** function.
```
Web3ProviderEngine.prototype.send = function(payload){
  throw new Error('Web3ProviderEngine does not support synchronous requests.')
}
```

Should Web3ProviderEngine also align with HttpProvider and WebsocketProvider implementation?

**Comment by hayesgm** [comment]
FWIW, I monkey-patched this by running:

`providerEngine.send = providerEngine.sendAsync;`

**Comment by j10sanders** [comment]
Same issue here.  I'm using the ProviderEngine for ledger support, and I can't use send.  sendAsync works for now, but I understand it will be deprecated soon.

**Comment by mcmire** [comment]
Sorry you were having trouble. Just an FYI: we are actively phasing out this package in favor of `json-rpc-engine` and its related packages. If you need help with an equivalent example using that stack, let us know and we can assist you further. I'm going to close this in the meantime.
