### ISSUE TITLE
Get RPC endpoint url from Metamask

### ISSUE THREAD

**Issue by pklinger** [MetaMask/web3-provider-engine#312]
Is it possible to receive the connected RPC endpoint URL from Metamask in the client somehow? I couldn't find the functionality after some search, but I'm wondering why this doesn't exist. It would really make sense in some cases.

I want to display the connected network-endpoint (url/ip address and port), not just the network id as offered by the `currentProvider` object. I would expect some value like "host" to display the connection endpoint, that I am able to enter in Metamask to estable a network connection.

Is there a way to get this value?

**Comment by kumavis** [comment]
no, that is a privacy concern for the user

you can get network id and chain id
