### ISSUE TITLE
14.2.0 breaks hex value encoding

### ISSUE THREAD

**Issue by hkalodner** [MetaMask/web3-provider-engine#317]
According to the hex value encoding specification (https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding). `0` values should be encoded as `"0x0"`. However the current implementation of bufferToQuantityHex  https://github.com/MetaMask/web3-provider-engine/blob/5f7acf6c96028f151b5d3ad2a99cb935056f2b71/util/rpc-hex-encoding.js#L17-L22 converts `0` to `"0x"`. This behavior was changed in a3172d6e1cbf01fc0e67e7ed30f4b4763b5ab1ca.

This was discovered trying to use ganache-core which updated from 14.1.0 to 14.2.0 of this package in its 2.6.1 release. Ganache now returns results for the newHeads subscription which are invalid since it uses a difficulty of 0. This causes go-ethereum to fail when subscribing to get block headers due to its strict adherence to the spec in https://github.com/ethereum/go-ethereum/blob/dbb03fe9893dd19f6b1de1ee3b768317f22fd135/common/hexutil/json.go#L358.

**Comment by kumavis** [comment]
patched in `web3-provider-engine@14.2.1`

**Comment by hkalodner** [comment]
Thanks!
