### ISSUE TITLE
Typescript types missing for versions ^15.0.0

### ISSUE THREAD

**Issue by javier-tarazaga** [MetaMask/web3-provider-engine#325]
Hi guys! 

There are more and more of us who are coding using Typescript and atm we can't use the latest version of this lib without having to provide our own types as the only types available (https://www.npmjs.com/package/@types/web3-provider-engine?activeTab=readme) is up to version 14.0.0. 

By any means, would you be able to provide official typings? 

Thanks!

**Comment by whymarrh** [comment]
> By any means, would you be able to provide official typings?

This project is not actively maintained:

> Originally created for MetaMask, but has been superceded by [json-rpc-engine](https://www.npmjs.com/package/json-rpc-engine) in combination with our [eth-json-rpc-middleware](https://www.npmjs.com/package/eth-json-rpc-middleware). This module is not very actively maintained, so we recommend using that one instead.

Both those suggested repositories will soon see 1st-party TypeScript support.

**Comment by mcmire** [comment]
Closing this as the original comment above still stands -- we will only be making critical fixes to this package going forward.
