### ISSUE TITLE
Provide an option to disable connection-request popup

### ISSUE THREAD

**Issue by dong77** [MetaMask/web3-provider-engine#326]
We want our dApp to automatically connect to MetaMask if the connection-request has already been approved; otherwise, we want the auto-connect to fail silently so the user will need to click a button to trigger the connection-request popup manually. Therefore, we need a parameter `noPopup` for the `window.etheruem.enable()` function.

When our dApp loads, we'll call `window.ethereum.enable(true)`; when a user clicks a button, we'll invoke `window.ethereum.enable(false)`. We believe this will enable a better user experience.

**Comment by mcmire** [comment]
Thanks for the idea. We have effectively deprecated this package, however, in favor of `json-rpc-engine` and its related packages, and are no longer taking feature requests. Please let us know if you need help using the new stack. I'm going to close this issue in the meantime.
