### ISSUE TITLE
```

### ISSUE THREAD

**Issue by miranda76** [MetaMask/web3-provider-engine#331]
```
TypeError: Cannot read property 'EIP712Domain' of undefined
    at Object.findTypeDependencies (/home/circleci/project/node_modules/eth-sig-util/index.js:100:47)
```
and other errors

_Originally posted by @kumavis in https://github.com/MetaMask/web3-provider-engine/pull/304#issuecomment-472282413_

**Comment by whymarrh** [comment]
Please open a new issue with a description and title
