### ISSUE TITLE
eth_blockNumber Invalid Request

### ISSUE THREAD

**Issue by BrendanChou** [MetaMask/web3-provider-engine#332]
Still broken in v15.0.2 (where it was labeled as fixed) and v15.0.6 (latest at the time of writing this)

Same issue as described in https://github.com/MetaMask/web3-provider-engine/issues/311 . Ideally the issue should be re-opened but it has not been despite multiple reports of it being broken, so I created a new issue.

**Comment by kumavis** [comment]
fix in the rpcprovider in 15.0.12, likely still present for websocket

**Comment by mcmire** [comment]
Sorry you were having trouble. Just an FYI: we are actively phasing out this package in favor of `json-rpc-engine` and its related packages and are no longer applying any fixes (aside from security-related ones), so I'm going to close this.
