### ISSUE TITLE
VmSubprovider seems to be abandoned

### ISSUE THREAD

**Issue by forshtat** [MetaMask/web3-provider-engine#341]
Hey! I have recently tried to use the provider engine with VmSubprovider and it failed to execute view functions that included some newly added opcodes. Looking into sources of vm.js i notice that VM is created with ```{enableHomestead: true }```, suggesting it has been a while.

So the question is - is VmSubprovider still maintained? Is there a way to use it with modern-day Ethereum mainnet?

I can try to create a small repo to reproduce an issue if it is an unexpected behavior.

**Comment by kumavis** [comment]
correct, VmSubprovider has not been maintained
I would investigate `ganache-core` for their implementation
