### ISSUE TITLE
Callback is undefined in signTransaction function

### ISSUE THREAD

**Issue by MicrowaveDev** [MetaMask/web3-provider-engine#343]
Looks like signTransaction is not correctly calling inside finalizeAndSubmitTx waterfall. I'm trying to implement signTransaction, but cb argument is not defined.

Code:
```
engine.addProvider(new HookedWalletSubprovider({
    signTransaction: async function (txParams, cb) {
      cb(null, client.signTransaction(txParams));
    }
});
```
Error:
```
instrument.ts:129 TypeError: cb is not a function
    at HookedWalletSubprovider.signTransaction
```

**Comment by mcmire** [comment]
As stated in the above PR, we're no longer taking pull requests for fixes, so I'm going to close this issue.
