### ISSUE TITLE
Upgrade ethereumjs-util & eth-sig-util

### ISSUE THREAD

**Issue by pi0neerpat** [MetaMask/web3-provider-engine#345]
I'm hoping we can upgrade these two packages to the latest versions. My ultimate goal is to eliminate duplicate bn.js packages due to version mismatching (discussed [here](https://github.com/pedrouid/enc-utils/issues/3#issuecomment-656887026)). I will create a PR soon to test this out, but just wanted to start here with a comment first.

P.s. Wallet Connect depends on this package. I made an issue discuss if/how to migrate away from web3-provider-engine. Any help (comments, articles, etc.) would be greatly appreciated! https://github.com/WalletConnect/walletconnect-monorepo/issues/310

**Comment by pi0neerpat** [comment]
So.... I did more digging and I don't think this will actually fix things. There are too many dependencies here which rely on bn.js version 4. This is quite a shame since bn.js is a fairly large package, it is used everywhere, and it is stuck in dependency hell.

**Comment by gakonst** [comment]
:+1: on updating ethereumjs-util and all related ethereumjs dependencies, given that they introduce the scrypt/node-gyp dependency hell in all downstream packages! @danfinlay is anyone working on this?

**Comment by schoenwaldnils** [comment]
I don't know if this issue is related, but because of the `eth-sig-util`dependency to a github repo my `npm install` on github actions if failing 🤔

```
└─┬ web3-react@5.0.5
  └─┬ @0x/subproviders@4.1.2
    ├─┬ ganache-core@2.13.2
    │ ├─┬ eth-sig-util@3.0.0
    │ │ └── ethereumjs-abi@0.6.5
    │ ├── ethereumjs-abi@0.6.8
    │ └─┬ web3-provider-engine@14.2.1
    │   └─┬ eth-sig-util@1.4.2
    │     └── ethereumjs-abi@0.6.8  (git+https://github.com/ethereumjs/ethereumjs-abi.git#1a27c59c15ab1e95ee8e5c4ed6ad814c49cc439e)
    └─┬ web3-provider-engine@14.0.6
      └─┬ eth-sig-util@1.4.2
        └── ethereumjs-abi@0.6.8  (git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#1a27c59c15ab1e95ee8e5c4ed6ad814c49cc439e)
```

They fixed this 2018 in eth-sig-util@2.0.2 😅 
https://github.com/MetaMask/eth-sig-util/pull/25

**Comment by vlapo** [comment]
Same problem as @schoenwaldnils. Could you please update this dependency

**Comment by cj-clifton** [comment]
Also have trouble with these dependencies. Any updates?

**Comment by mcmire** [comment]
We have effectively deprecated this project, so unless there is a security issue with any of the dependencies, we are not working on updating them. We recommend that you use [`json-rpc-engine`](https://github.com/MetaMask/json-rpc-engine), as that package is what we've moved to internally and provides all of the functionality of this package in a more sensible form.
