### ISSUE TITLE
Invalid request with parity/open-ethereum

### ISSUE THREAD

**Issue by rb-iexec** [MetaMask/web3-provider-engine#346]
Hi,

I use truffle + truffle-privatekey-provider connected to a parity node.  
truffle-privatekey-provider is a package using web3-provider-engine.

The problem is web3-provider-engine use the flag `skip-cache=true ` inside rpc calls and parity/openethereum sees it as a bad request, making it unusable for me. It would be nice to have the possibility somewhere to set this to false before any calls.

**Comment by mcmire** [comment]
Sorry you were having trouble. Just an FYI: we don't recommend using this package any more as we actively phasing it out in favor of `json-rpc-engine` and its related packages, which is more modernized/simplified and removes this bug. Let us know if you need further help. I'm going to close this in the meantime.
