### ISSUE TITLE
Upgrade guide for 14 -> 15

### ISSUE THREAD

**Issue by davidmurdoch** [MetaMask/web3-provider-engine#358]
v14-15  was a breaking change and the only information I could find was in the [CHANGELOG](https://github.com/MetaMask/web3-provider-engine/blob/master/CHANGELOG.md#1500), but it doesn't actually describe how to update things.

Is there an upgrade guide somewhere I just can't find?

**Comment by davidmurdoch** [comment]
We are using it in ganache-core here: https://github.com/trufflesuite/ganache-core/blob/c2288f497aa401ca9ef2c36844581a15774734fa/lib/provider.js#L27-L52

If I update to v15 (or v16) I get an error, `subscriptionSubprovider.on is not a function`.

I imagine this is because "TypeError: subscriptionSubprovider.on is not a function" now, so removing the `.on` is obviously part of the fix... but what does "to provider?" mean here?

I tried `this.engine`, thinking "provider" was short for "provider-engine", but that doesn't seem to emit a `data` event.

It also seems as though `eth_newFilter` is no longer supported but the SubProvider; is there a way of getting that back?

note: I've updated our internal block-tracker based on its v4 [CHANGELOG](https://github.com/MetaMask/eth-block-tracker/blob/master/CHANGELOG.md#400), and appears to work?

**Comment by mcmire** [comment]
Just an FYI: we are actively phasing out this package in favor of `json-rpc-engine` and its related packages, so I'm going to close this. It appears that the file you linked to is long gone, but if you still need help, please reach out to me or a MetaMask channel in Slack.
