### ISSUE TITLE
Publish latest changes to NPM

### ISSUE THREAD

**Issue by VladimirMikulic** [MetaMask/web3-provider-engine#426]
The last NPM release was 8 months ago.

However, I saw you merged https://github.com/MetaMask/web3-provider-engine/pull/409 recently which fixes this warning for me on Yarn:
![Screenshot_20221220_0247519](https://user-images.githubusercontent.com/35997844/209054518-d63862f5-a745-4d0b-929e-f46e05ff9315.png)

Could you please release the patch to NPM so we don't get this warning anymore?

Thanks!

**Comment by mcmire** [comment]
We've released 16.0.5, so that warning should be gone going forward.

**Comment by VladimirMikulic** [comment]
Thank you so much @mcmire!
