### ISSUE TITLE
'Validator' provider

### ISSUE THREAD

**Issue by axic** [MetaMask/web3-provider-engine#51]
A validator is a (sub)provider, which transmits all queries to two (or more) (sub)providers, compares the results, returns an error if they don't match, otherwise transmits the actual result.

That it is the basic concept, however there are many edge cases to be considered. For one: what happens if a legit transaction was processed and the two endpoints don't have the same processing speed?

Even `sendRawTransaction` should be possible to be sent to multiple endpoints given the identical nonce will ensure it is only executed once.

**Comment by flyswatter** [comment]
If you specify a timeout length, this could be a nice way to provide resilience.

- Dan

**Comment by kumavis** [comment]
this is interesting -- pairs nicely with the block polling factored out, bc then we have a bunch of ways of combining subproviders
```
providerStack
providerParallel
providerAny
```

**Comment by kumavis** [comment]
lol this lib may eventually just boil down to some flow contraol library like `rx.js`. i have no problem with that.

**Comment by mcmire** [comment]
Thanks for the ideas, but we are actively phasing out this package in favor of `json-rpc-engine` and its related packages and are no longer accepting additions, so I'm going to close this.
