### ISSUE TITLE
Test - batch requests

### ISSUE THREAD

**Issue by tcoulter** [MetaMask/web3-provider-engine#6]
TODO

**Comment by kumavis** [comment]
we should make sure we are handling them correctly, especially in error cases

**Comment by aakilfernandes** [comment]
Looks like somethings not right with the error handling of batch requests. If there is a bad request sandwiched between two good requests, the last (third) request does not get included in the return. looking into this now

**Comment by aakilfernandes** [comment]
You can reproduce by installing/running tests of ultralightbeam

https://github.com/SafeMarket/ultralightbeam/blob/master/test/rejection.js#L43-L45
