### ISSUE TITLE
"Emulate"/"Substitute" provider

### ISSUE THREAD

**Issue by axic** [MetaMask/web3-provider-engine#60]
I think it would make sense to move some of the substitution code into its own provider. By this I mean official RPC methods which can be emulated by other RPC methods.

One of them is the recent eth_getLogs in etherscan.  Maybe there are other which fit the bill?

**Comment by kumavis** [comment]
yeah a provider or utility fn or somn

**Comment by mcmire** [comment]
Thanks for the ideas, but we are actively phasing out this package in favor of `json-rpc-engine` and its related packages and are no longer accepting additions, so I'm going to close this.
